// ============================================
// CATÁLOGO DE PRODUTOS - ALL THINGS STORE
// Para editar preços ou adicionar produtos, modifique este arquivo
// ============================================

const CATEGORIES = {
  angel: { name: 'Angel', subtitle: 'Mães e Namorados' },
  lacreme: { name: 'laCreme', subtitle: 'Cremosidade indulgente' },
  intenso: { name: 'Bendito Cacao', subtitle: 'Sabores intensos' },
  bless: { name: 'Bless', subtitle: 'Zero açúcar e lactose' },
  lanut: { name: 'LaNut', subtitle: 'Avelã e Pistache' },
  dreams: { name: 'Dreams', subtitle: 'Sobremesas em tablete' },
  classicos: { name: 'Clássicos', subtitle: 'Sabores que nunca saem de moda' },
  biscoiteria: { name: 'Biscoiteria', subtitle: 'Biscoitos, cookies e wafers' },
  trufas: { name: 'Trufas', subtitle: 'Pequenas porções de alegria' },
  tabletes: { name: 'Tabletes', subtitle: 'Para todo momento' },
  bombons: { name: 'Bombons', subtitle: 'Petit Deli e Bytes' },
  harrypotter: { name: 'Harry Potter', subtitle: 'Edição limitada' },
  infantil: { name: 'Infantil', subtitle: 'Kids, Miau e Chocomonstros' },
  presentes: { name: 'Presentes', subtitle: 'Caixas e cestas' },
  acessorios: { name: 'Acessórios', subtitle: 'Canecas, bolsas e chaveiros' }
};

const PRODUCTS = [
  // ===== ANGEL =====
  { id: '1003308', name: 'Tabletes Angel', price: 32.49, weight: '90g', desc: 'Caixa com 3 tabletes ao leite de 30 gramas cada', category: 'angel' },
  { id: '1002333', name: 'Botão de Rosa Angel', price: 21.29, weight: '13,3g', desc: 'Bombom de chocolate ao leite com recheio de brigadeiro', category: 'angel' },
  { id: '1001045', name: 'Caixa Artesanal Delícias de Amor', price: 67.99, weight: '153g', desc: 'Bombons sortidos com tablete decorado com chocolate branco', category: 'angel' },
  { id: '1003946', name: 'Lata Bombom Angel', price: 39.49, weight: '100g', desc: 'Bombons ao leite com recheios de avelã e doce de leite', category: 'angel' },
  { id: '1003011', name: 'Minicubo Mezzo', price: 21.29, weight: '70g', desc: 'Drageados crocantes ao leite e chocolate branco', category: 'angel' },
  { id: '1003530', name: 'Caixa Angel Porta-joias', price: 79.99, weight: '185g', desc: 'Bombons ao leite e branco com recheios variados e avelã', category: 'angel' },
  { id: '1003290', name: 'Caixa Angel Coleção Sortidos', price: 129.99, weight: '290g', desc: 'Bombons sortidos com baunilha, wafer, morango, cereja e avelã', category: 'angel' },
  { id: '1003954', name: 'Caixa Angel Coleção Sortidos M', price: 64.99, weight: '120g', desc: 'Bombons com baunilha, wafer, morango e caramelo com sal', category: 'angel' },
  { id: '1003334', name: 'Caixa Corações', price: 26.99, weight: '75g', desc: 'Bombons ao leite com recheio sabor frutas silvestres', category: 'angel' },
  { id: '1000191', name: 'Cerejão', price: 8.49, weight: '23g', desc: 'Bombom ao leite com recheio de cereja ao licor', category: 'angel' },
  { id: '1003333', name: 'Angel Gourmet', price: 61.99, weight: '200g', desc: 'Bombons sabores geleia de morango e trufa intensa', category: 'angel' },

  // ===== LACREME =====
  { id: '1003608', name: 'Trufa laCreme Mezzo', price: 3.79, weight: '13,5g', desc: 'Trufa de chocolate ao leite com recheio ao leite e branco', category: 'lacreme' },
  { id: '1004022', name: 'Caixa laCreme Sortidos', price: 109.99, weight: '260g', desc: 'Tabletes e bombons ao leite, branco e pasta de pistache', category: 'lacreme' },
  { id: '1002628', name: 'Minishow laCreme', price: 42.49, weight: '108g', desc: 'Bombons ao leite com recheio de trufa de chocolate', category: 'lacreme' },
  { id: '1003102', name: 'Minishow laCreme Mezzo', price: 42.49, weight: '108g', desc: 'Bombons ao leite e branco com trufa ao leite e branco', category: 'lacreme' },
  { id: '1003981', name: 'Minishow laCreme Gianduia', price: 42.49, weight: '108g', desc: 'Bombons ao leite com recheio de creme de avelã', category: 'lacreme' },
  { id: '1003980', name: 'Minishow laCreme Pistache', price: 42.49, weight: '108g', desc: 'Bombons ao leite e branco com creme de pistache', category: 'lacreme' },
  { id: '1003774', name: 'Tablete Duo Intense', price: 24.49, weight: '100g', desc: 'Chocolate ao leite e chocolate intenso laCreme', category: 'lacreme' },
  { id: '1003788', name: 'Tablete Pistache', price: 24.49, weight: '100g', desc: 'Chocolate branco laCreme e pasta de pistache', category: 'lacreme' },
  { id: '1003637', name: 'Tablete Gold', price: 21.29, weight: '100g', desc: 'Chocolate branco caramelizado laCreme', category: 'lacreme' },
  { id: '1003790', name: 'Tablete Gianduia', price: 21.29, weight: '100g', desc: 'Chocolate ao leite laCreme e pasta de avelã', category: 'lacreme' },
  { id: '1002638', name: 'Tablete Ao Leite 100g', price: 21.29, weight: '100g', desc: 'Chocolate ao leite laCreme', category: 'lacreme' },
  { id: '1002866', name: 'Tablete Branco 100g', price: 21.29, weight: '100g', desc: 'Chocolate branco laCreme', category: 'lacreme' },
  { id: '1003107', name: 'Tablete Mezzo 100g', price: 21.29, weight: '100g', desc: 'Chocolate ao leite e chocolate branco laCreme', category: 'lacreme' },
  { id: '1002789', name: 'Ao Leite Zero Açúcar', price: 26.49, weight: '100g', desc: 'Chocolate ao leite laCreme sem adição de açúcares', category: 'lacreme' },
  { id: '1003054', name: 'Branco Zero Açúcar', price: 26.49, weight: '100g', desc: 'Chocolate branco laCreme sem adição de açúcares', category: 'lacreme' },
  { id: '1002820', name: 'Ao Leite Zero Lactose', price: 26.49, weight: '100g', desc: 'Chocolate ao leite laCreme sem lactose', category: 'lacreme' },
  { id: '1000624', name: 'Caixa Trufas laCreme', price: 42.49, weight: '160g', desc: 'Trufas sortidas nos sabores chocolate branco e ao leite', category: 'lacreme' },
  { id: '1001867', name: 'Slack laCreme', price: 37.49, weight: '315g', desc: 'Creme com cacau sabor chocolate ao leite', category: 'lacreme' },
  { id: '1003997', name: 'Slack laCreme Gianduia', price: 37.49, weight: '315g', desc: 'Creme de avelã laCreme', category: 'lacreme' },

  // ===== INTENSO (BENDITO CACAO) =====
  { id: '1002627', name: 'Minishow Bendito Cacao', price: 42.49, weight: '108g', desc: 'Bombons recheados com trufa de chocolate intenso', category: 'intenso' },
  { id: '1002648', name: '55% Cacau Trufado', price: 5.29, weight: '30g', desc: 'Chocolate 55% cacau com recheio de chocolate intenso', category: 'intenso' },
  { id: '1003059', name: 'Tablete Dark Milk 5g', price: 1.39, weight: '5g', desc: 'Chocolate ao leite 55% cacau', category: 'intenso' },
  { id: '1002945', name: 'Tablete 85% Cacau 5g', price: 1.39, weight: '5g', desc: 'Chocolate intenso 85% cacau', category: 'intenso' },
  { id: '1002948', name: 'Tablete 70% Cacau 5g', price: 1.39, weight: '5g', desc: 'Chocolate intenso 70% cacau', category: 'intenso' },
  { id: '1002188', name: 'Trufa 70% Cacau', price: 3.79, weight: '13,5g', desc: 'Chocolate 70% cacau com recheio de trufa intensa', category: 'intenso' },
  { id: '1003830', name: 'Tablete 86% Cacau 30g', price: 12.99, weight: '30g', desc: 'Chocolate intenso 86% cacau', category: 'intenso' },
  { id: '1003829', name: 'Tablete 72% Cacau 30g', price: 12.99, weight: '30g', desc: 'Chocolate intenso 72% cacau', category: 'intenso' },
  { id: '1003060', name: 'Dark Milk 100g', price: 26.49, weight: '100g', desc: 'Chocolate ao leite 55% cacau Tree to Bar', category: 'intenso' },
  { id: '1002620', name: 'Tablete 55% Cacau 20g', price: 5.29, weight: '20g', desc: 'Tablete de chocolate 55% cacau', category: 'intenso' },
  { id: '1003612', name: 'Tablete 72% Cacau 100g', price: 26.49, weight: '100g', desc: 'Chocolate intenso 72% cacau', category: 'intenso' },
  { id: '1003613', name: 'Tablete 86% Cacau 100g', price: 26.49, weight: '100g', desc: 'Chocolate intenso 86% cacau', category: 'intenso' },
  { id: '1002823', name: 'Dedo de Deus 67%', price: 26.49, weight: '100g', desc: 'Chocolate 67% cacau da Fazenda Dedo de Deus', category: 'intenso' },
  { id: '1002485', name: 'Caixa Bendito Cacao', price: 64.99, weight: '170g', desc: 'Bombons sortidos intensos com nibs de cacau e morango', category: 'intenso' },
  { id: '1003124', name: 'Caixa Tabletes Intensidade G', price: 129.99, weight: '350g', desc: 'Tabletes 5g em sabores variados de cacau', category: 'intenso' },
  { id: '1002495', name: 'Caixa Tabletes Intensidade P', price: 39.49, weight: '150g', desc: 'Tabletes 5g em sabores selecionados', category: 'intenso' },

  // ===== BLESS =====
  { id: '1003722', name: 'Drageado Castanhas e Uvas-passas', price: 47.99, weight: '150g', desc: 'Castanhas-de-caju e uvas-passas com chocolate ao leite zero açúcar', category: 'bless' },
  { id: '1003466', name: 'Drageado Bless ao Leite', price: 39.49, weight: '150g', desc: 'Drageados de chocolate ao leite zero adição de açúcares', category: 'bless' },
  { id: '1003453', name: 'Bombom Avelã Zero Açúcar', price: 5.29, weight: '13,5g', desc: 'Bombom ao leite com recheio cremoso de avelã', category: 'bless' },
  { id: '1003715', name: 'Bombom Ao Leite Zero Açúcar', price: 5.29, weight: '13,5g', desc: 'Bombom de chocolate ao leite com recheio ao leite', category: 'bless' },
  { id: '1003454', name: 'Bombom Avelã Zero Lactose', price: 5.29, weight: '13,5g', desc: 'Bombom ao leite com recheio de avelã sem lactose', category: 'bless' },
  { id: '1003298', name: 'Miau Bless Zero Lactose', price: 24.49, weight: '70g', desc: 'Chocolate ao leite zero lactose em formato de língua de gato', category: 'bless' },
  { id: '1003471', name: 'Cubo Bless Avelã Zero Açúcar', price: 39.49, weight: '145g', desc: 'Bombons ao leite com recheio de avelã zero açúcar', category: 'bless' },
  { id: '1003390', name: 'Tablete Branco Zero Açúcar', price: 6.99, weight: '20g', desc: 'Tablete de chocolate branco zero adição de açúcares', category: 'bless' },
  { id: '1003389', name: 'Tablete 70% Cacau Zero', price: 6.99, weight: '20g', desc: 'Tablete 70% cacau zero adição de açúcares', category: 'bless' },
  { id: '1003391', name: 'Tablete Ao Leite Zero', price: 6.99, weight: '20g', desc: 'Tablete ao leite zero adição de açúcares', category: 'bless' },
  { id: '1003725', name: 'Castanha-de-caju Zero', price: 6.99, weight: '20g', desc: 'Tablete ao leite zero açúcar com pedaços de castanha', category: 'bless' },
  { id: '1003714', name: 'Tablete Zero Lactose', price: 6.99, weight: '20g', desc: 'Tablete de chocolate ao leite zero lactose', category: 'bless' },
  { id: '1003392', name: 'Trufa Branca Zero Açúcar', price: 6.99, weight: '30g', desc: 'Trufa de chocolate branco zero açúcar', category: 'bless' },
  { id: '1003396', name: 'Trufa Ao Leite Zero Açúcar', price: 6.99, weight: '30g', desc: 'Trufa de chocolate ao leite zero açúcar', category: 'bless' },

  // ===== LANUT =====
  { id: '1000003', name: 'Drageado LaNut', price: 31.99, weight: '150g', desc: 'Avelãs torradas e cobertas com chocolate ao leite', category: 'lanut' },
  { id: '1002642', name: 'Trufa LaNut Avelã', price: 6.49, weight: '30g', desc: 'Chocolate ao leite com recheio de creme de avelã', category: 'lanut' },
  { id: '1002598', name: 'Tablete LaNut 20g', price: 5.29, weight: '20g', desc: 'Chocolate ao leite com pasta de avelã', category: 'lanut' },
  { id: '1003193', name: 'Tablete LaNut Pistache Recheado', price: 31.99, weight: '130g', desc: 'Tablete ao leite e branco recheado com creme e pedaços de pistache', category: 'lanut' },
  { id: '1003636', name: 'Tablete LaNut Pistache Dubai', price: 36.99, weight: '130g', desc: 'Tablete ao leite recheado com creme de pistache e kataifi', category: 'lanut' },
  { id: '1002643', name: 'Tablete LaNut Branco', price: 21.29, weight: '100g', desc: 'Chocolate branco com pasta de avelã', category: 'lanut' },
  { id: '1003639', name: 'Slack LaNut Pistache', price: 69.99, weight: '290g', desc: 'Creme de pistache', category: 'lanut' },
  { id: '1003694', name: 'Drageado LaNut Pistache', price: 31.99, weight: '150g', desc: 'Pistaches inteiros cobertos com chocolate branco', category: 'lanut' },
  { id: '1001706', name: 'Petit Deli Pistache', price: 21.29, weight: '78g', desc: 'Bombons ao leite com creme de pistache cobertos com branco', category: 'lanut' },
  { id: '1003394', name: 'Trufa LaNut Pistache', price: 6.49, weight: '30g', desc: 'Chocolate ao leite com recheio de creme de pistache', category: 'lanut' },

  // ===== DREAMS =====
  { id: '1004034', name: 'Mil-folhas Avelã Premiado', price: 26.49, weight: '130g', desc: 'Chocolate ao leite com creme mil-folhas e avelã', category: 'dreams' },
  { id: '1004033', name: 'Mil-folhas Premiado', price: 26.49, weight: '130g', desc: 'Chocolate ao leite com recheio cremoso mil-folhas', category: 'dreams' },
  { id: '1004037', name: 'Pistache Premiado', price: 31.99, weight: '130g', desc: 'Chocolate ao leite e branco com creme e pedaços de pistache', category: 'dreams' },
  { id: '1004036', name: 'Speculoos Premiado', price: 26.49, weight: '130g', desc: 'Chocolate ao leite e branco com biscoito de especiarias', category: 'dreams' },
  { id: '1002880', name: 'Mil-folhas Dreams', price: 26.49, weight: '130g', desc: 'Chocolate ao leite com recheio cremoso mil-folhas', category: 'dreams' },
  { id: '1002881', name: 'Mil-folhas Avelã Dreams', price: 26.49, weight: '130g', desc: 'Chocolate ao leite com mil-folhas e creme de avelã', category: 'dreams' },
  { id: '1002882', name: 'Torta de Maracujá Dreams', price: 26.49, weight: '130g', desc: 'Chocolate ao leite com torta de maracujá e biscoito', category: 'dreams' },
  { id: '1003339', name: 'Crème Brûlée Dreams', price: 26.49, weight: '130g', desc: 'Chocolate ao leite e branco sabor crème brûlée', category: 'dreams' },
  { id: '1003103', name: 'Torta de Morango Dreams', price: 26.49, weight: '130g', desc: 'Chocolate ao leite sabor torta de morango com biscoito', category: 'dreams' },

  // ===== CLÁSSICOS =====
  { id: '1003994', name: 'Cubo Brigadeiro', price: 31.99, weight: '130g', desc: 'Bombons ao leite com recheio de brigadeiro', category: 'classicos' },
  { id: '1000507', name: 'Chocoarte Te Amo', price: 16.99, weight: '40g', desc: 'Tablete decorado com chocolate branco', category: 'classicos' },
  { id: '1002768', name: 'Caixa Clássicos', price: 39.49, weight: '120g', desc: 'Bombons com recheios de trufa, cereja ao licor e avelã', category: 'classicos' },
  { id: '1003111', name: 'Caixa Bombons Sortidos', price: 74.99, weight: '240g', desc: 'Bombons sortidos com trufa, ao leite e branco', category: 'classicos' },
  { id: '1004027', name: 'Fondue', price: 59.99, weight: '250g', desc: 'Creme de chocolate para fondue', category: 'classicos' },
  { id: '1001474', name: 'Caixa Clássicos Sortidos G', price: 74.99, weight: '360g', desc: 'Bombons ao leite com trufa tradicional, avelã e cereja', category: 'classicos' },
  { id: '1002770', name: 'Caixa Clássicos Sortidos M', price: 59.99, weight: '160g', desc: 'Bombons ao leite com sabores sortidos', category: 'classicos' },
  { id: '1002515', name: 'Garrafinhas', price: 28.49, weight: '88g', desc: 'Garrafinhas com licor de cereja, marula e conhaque', category: 'classicos' },
  { id: '1002441', name: 'Drageado Licor', price: 31.99, weight: '150g', desc: 'Drageado ao leite com licor de conhaque', category: 'classicos' },
  { id: '1003872', name: 'Caixa Gourmet', price: 149.99, weight: '465g', desc: 'Bombons sortidos: pistache, laranja, avelã, brownie e mais', category: 'classicos' },
  { id: '1002770b', name: 'Golden Gift', price: 59.99, weight: '160g', desc: 'Bombons ao leite com trufa, cereja ao licor e avelã', category: 'classicos' },
  { id: '1004025', name: 'Caixa CS Bombons Sortidos M', price: 89.99, weight: '160g', desc: 'Bombons com avelã, caramelo com sal, morango e pistache', category: 'classicos' },
  { id: '1004024', name: 'Caixa CS Bombons Sortidos G', price: 129.99, weight: '300g', desc: 'Bombons sortidos premium em vários sabores', category: 'classicos' },

  // ===== BISCOITERIA =====
  { id: '1003719', name: 'Biscoito Tradicional', price: 13.99, weight: '85g', desc: 'Biscoitos de baunilha com base de chocolate ao leite', category: 'biscoiteria' },
  { id: '1003090', name: 'Biscoito Coberto Tradicional', price: 16.99, weight: '100g', desc: 'Biscoitos cobertos com chocolate ao leite e branco', category: 'biscoiteria' },
  { id: '1003113', name: 'Biscoito Coberto Speculoos', price: 16.99, weight: '100g', desc: 'Biscoitos de especiarias cobertos com chocolate', category: 'biscoiteria' },
  { id: '1003682', name: 'Drageado Biscoiteria Speculoos', price: 19.99, weight: '100g', desc: 'Pedaços de biscoito de especiarias drageados', category: 'biscoiteria' },
  { id: '1003352', name: 'Lata Biscoiteria Sortidos', price: 84.99, weight: '265g', desc: 'Cookies, biscoitos e wafers sortidos', category: 'biscoiteria' },
  { id: '1001471', name: 'Porta-joias Cacau Show', price: 99.99, weight: '162g', desc: 'Bombons ao leite com avelã e doce de leite', category: 'biscoiteria' },
  { id: '1003345', name: 'Cookies Chocolate ao Leite', price: 11.99, weight: '40g', desc: 'Cookies de baunilha com gotas de chocolate', category: 'biscoiteria' },
  { id: '1003118', name: 'Biscoito Coberto Tradicional 50g', price: 11.99, weight: '50g', desc: 'Biscoitos cobertos com chocolate ao leite', category: 'biscoiteria' },
  { id: '1003344', name: 'Cookies Triplo Chocolate', price: 21.29, weight: '140g', desc: 'Cookies de chocolate com gotas branco e intenso', category: 'biscoiteria' },
  { id: '1003343', name: 'Cookies de Limão', price: 21.29, weight: '140g', desc: 'Cookies de limão com gotas de chocolate', category: 'biscoiteria' },
  { id: '1003087', name: 'Cookies Gotas de Chocolate', price: 18.29, weight: '120g', desc: 'Cookies de baunilha com gotas de chocolate ao leite', category: 'biscoiteria' },
  { id: '1004001', name: 'Wafer Mil-folhas Coberto', price: 11.99, weight: '32g', desc: 'Wafers com mil-folhas cobertos de chocolate', category: 'biscoiteria' },
  { id: '1004000', name: 'Wafer Avelã Coberto', price: 11.99, weight: '32g', desc: 'Wafers com avelã cobertos de chocolate', category: 'biscoiteria' },
  { id: '1003347', name: 'Wafer Coberto', price: 23.49, weight: '80g', desc: 'Wafers cobertos com chocolate ao leite', category: 'biscoiteria' },
  { id: '1001980', name: 'Wafer Recheado Mil-folhas', price: 16.99, weight: '80g', desc: 'Wafers com recheio sabor mil-folhas', category: 'biscoiteria' },
  { id: '1003082', name: 'Wafer LaNut Avelã', price: 16.99, weight: '80g', desc: 'Wafers com recheio de creme de avelã', category: 'biscoiteria' },
  { id: '1003687', name: 'Wafer de Cacau', price: 16.99, weight: '80g', desc: 'Wafers de cacau com recheio sabor leite', category: 'biscoiteria' },
  { id: '1003183', name: 'Wafer LaNut Pistache', price: 19.29, weight: '80g', desc: 'Wafers com recheio de creme de pistache', category: 'biscoiteria' },

  // ===== TRUFAS =====
  { id: '1002604', name: 'Trufa Morango', price: 5.29, weight: '30g', desc: 'Ao leite com recheio de morango', category: 'trufas' },
  { id: '1002639', name: 'Trufa Maracujá', price: 5.29, weight: '30g', desc: 'Ao leite com recheio de maracujá', category: 'trufas' },
  { id: '1002641', name: 'Trufa Menta', price: 5.29, weight: '30g', desc: 'Ao leite com recheio de menta', category: 'trufas' },
  { id: '1002622', name: 'Trufa Coco', price: 5.29, weight: '30g', desc: 'Ao leite com recheio de coco', category: 'trufas' },
  { id: '1002724', name: 'Trufa Paçoca', price: 5.29, weight: '30g', desc: 'Ao leite com recheio de amendoim', category: 'trufas' },
  { id: '1002633', name: 'Trufa Tradicional', price: 5.29, weight: '30g', desc: 'Ao leite com recheio tradicional', category: 'trufas' },
  { id: '1002634', name: 'Trufa Branco', price: 5.29, weight: '30g', desc: 'Branco com recheio de chocolate branco', category: 'trufas' },
  { id: '1002616', name: 'Trufa Mezzo', price: 5.29, weight: '30g', desc: 'Mesclada de chocolate ao leite e branco', category: 'trufas' },
  { id: '1003424', name: 'Trufa Torta de Limão', price: 5.29, weight: '30g', desc: 'Branco com recheio sabor torta de limão', category: 'trufas' },
  { id: '1003138', name: 'Trufa Marula', price: 6.49, weight: '30g', desc: 'Chocolate ao leite com recheio sabor marula', category: 'trufas' },
  { id: '1003075', name: 'Trufa Cereja ao Licor', price: 6.49, weight: '30g', desc: 'Ao leite com recheio sabor cereja ao licor', category: 'trufas' },
  { id: '1002896', name: 'Trufa Petit Gâteau', price: 6.49, weight: '30g', desc: 'Ao leite com recheio sabor petit gâteau', category: 'trufas' },
  { id: '1002193', name: 'Trufa laCreme Ao Leite', price: 3.79, weight: '13,5g', desc: 'Chocolate ao leite com recheio de trufa', category: 'trufas' },
  { id: '1002194', name: 'Trufa laCreme Branco', price: 3.79, weight: '13,5g', desc: 'Chocolate branco com recheio de trufa branca', category: 'trufas' },
  { id: '1002195', name: 'Trufa laCreme Gianduia', price: 3.79, weight: '13,5g', desc: 'Trufa ao leite com recheio de avelã', category: 'trufas' },
  { id: '1003990', name: 'Trufa laCreme Pistache', price: 3.79, weight: '13,5g', desc: 'Trufa branca com creme de pistache', category: 'trufas' },

  // ===== TABLETES =====
  { id: '1002964', name: 'Tablete Café 5g', price: 1.39, weight: '5g', desc: 'Chocolate ao leite sabor café', category: 'tabletes' },
  { id: '1002962', name: 'Tablete Menta 5g', price: 1.39, weight: '5g', desc: 'Chocolate ao leite sabor menta', category: 'tabletes' },
  { id: '1002946', name: 'Tablete laCreme Branco 5g', price: 1.39, weight: '5g', desc: 'Chocolate branco', category: 'tabletes' },
  { id: '1002947', name: 'Tablete laCreme Ao Leite 5g', price: 1.39, weight: '5g', desc: 'Chocolate ao leite', category: 'tabletes' },
  { id: '1002600', name: 'Tablete laCreme 20g', price: 5.29, weight: '20g', desc: 'Chocolate ao leite laCreme', category: 'tabletes' },
  { id: '1002636', name: 'Tablete laCreme Branco 20g', price: 5.29, weight: '20g', desc: 'Chocolate branco laCreme', category: 'tabletes' },
  { id: '1002742', name: 'Tablete laCreme Mezzo 20g', price: 5.29, weight: '20g', desc: 'Chocolate ao leite e branco laCreme', category: 'tabletes' },
  { id: '1002599', name: 'Tablete Laranja 20g', price: 5.29, weight: '20g', desc: 'Chocolate ao leite sabor laranja', category: 'tabletes' },
  { id: '1002601', name: 'Tablete Castanha-de-caju', price: 5.29, weight: '20g', desc: 'Chocolate ao leite com castanha-de-caju', category: 'tabletes' },
  { id: '1002602', name: 'Tablete Crocante', price: 5.29, weight: '18g', desc: 'Chocolate ao leite com flocos de arroz', category: 'tabletes' },
  { id: '1002609', name: 'Tablete Pimenta', price: 5.29, weight: '20g', desc: 'Chocolate ao leite sabor pimenta', category: 'tabletes' },
  { id: '1002603', name: 'Tablete Ao Leite 20g', price: 5.29, weight: '20g', desc: 'Chocolate ao leite tradicional', category: 'tabletes' },
  { id: '1003096', name: 'Tablete Morango 100g', price: 19.29, weight: '100g', desc: 'Chocolate ao leite com morango', category: 'tabletes' },
  { id: '1003094', name: 'Tablete Castanha Caramelizada', price: 19.29, weight: '100g', desc: 'Ao leite com gianduia e crocante caramelizado', category: 'tabletes' },
  { id: '1002867', name: "Tablete Cookies'n Cream", price: 19.29, weight: '100g', desc: 'Chocolate branco com biscoito de chocolate', category: 'tabletes' },

  // ===== BOMBONS (PETIT DELI / BYTES) =====
  { id: '1002762', name: 'Petit Deli Mil-folhas', price: 21.29, weight: '78g', desc: 'Bombons ao leite com recheio mil-folhas', category: 'bombons' },
  { id: '1002765', name: "Petit Deli Cookies'n Cream", price: 21.29, weight: '80g', desc: 'Bombons ao leite com cookies cobertos de branco', category: 'bombons' },
  { id: '1002792', name: 'Petit Deli Brownie', price: 21.29, weight: '79g', desc: 'Bombons ao leite com recheio brownie e cookies', category: 'bombons' },
  { id: '1002968', name: 'Bytes Ao Leite Crocante', price: 19.99, weight: '100g', desc: 'Drageados crocantes de chocolate ao leite', category: 'bombons' },
  { id: '1002996', name: 'Bytes Branco Crocante', price: 19.99, weight: '100g', desc: 'Drageados crocantes de chocolate branco', category: 'bombons' },
  { id: '1003279', name: 'Bytes Amendoim', price: 19.99, weight: '100g', desc: 'Amendoins drageados com doce de leite e chocolate', category: 'bombons' },
  { id: '1002913', name: 'Bytes Uva-passa', price: 19.99, weight: '100g', desc: 'Drageados de uvas-passas com chocolate ao leite', category: 'bombons' },
  { id: '1003040', name: 'Bytes Ao Leite e Branco', price: 19.99, weight: '100g', desc: 'Drageados crocantes ao leite e branco', category: 'bombons' },
  { id: '1003099', name: 'Bytes 3 Chocolates', price: 19.99, weight: '100g', desc: 'Centro crocante com três camadas de chocolate', category: 'bombons' },
  { id: '1000024', name: 'Flocos de Arroz ao Leite', price: 18.99, weight: '100g', desc: 'Flocos de arroz crocantes cobertos com chocolate', category: 'bombons' },
  { id: '2000014', name: 'Wafer Avelã Bytes', price: 11.99, weight: '50g', desc: 'Wafer recheado com creme de avelã coberto de chocolate', category: 'bombons' },
  { id: '2000974', name: 'Wafer Sintonia', price: 11.99, weight: '45g', desc: 'Wafer com castanha-de-caju e canela', category: 'bombons' },

  // ===== HARRY POTTER =====
  { id: '2006505', name: 'Caneca Butterbeer', price: 89.99, weight: '480ml', desc: 'Caneca temática Cerveja Amanteigada - edição limitada', category: 'harrypotter' },
  { id: '1004031', name: 'Tablete Butterbeer', price: 5.29, weight: '18g', desc: 'Tablete ao leite sabor manteiga, baunilha e caramelo', category: 'harrypotter' },
  { id: '1004028', name: 'Trufa Butterbeer', price: 3.79, weight: '13,5g', desc: 'Trufa ao leite sabor manteiga, baunilha e caramelo', category: 'harrypotter' },
  { id: '1003374', name: 'Caixa Brasões Hogwarts', price: 57.99, weight: '140g', desc: 'Brasões de chocolate ao leite e branco', category: 'harrypotter' },
  { id: '1003239', name: 'Tablete Brasão Hogwarts', price: 16.99, weight: '54g', desc: 'Tablete ao leite e branco com card exclusivo', category: 'harrypotter' },
  { id: '1003448', name: 'Biscoito Harry Potter', price: 16.99, weight: '100g', desc: 'Biscoito com chocolate ao leite', category: 'harrypotter' },

  // ===== INFANTIL =====
  { id: '1001698', name: 'Cofre laCreme Kids', price: 59.99, weight: '150g', desc: 'Trufinhas ao leite em cofre formato Cremilda', category: 'infantil' },
  { id: '1002196', name: 'Trufa laCreme Kids', price: 3.79, weight: '13,5g', desc: 'Chocolate ao leite com recheio sabor leite', category: 'infantil' },
  { id: '1002635', name: 'Tablete laCreme Kids', price: 5.29, weight: '18g', desc: 'Chocolate ao leite com recheio sabor leite', category: 'infantil' },
  { id: '1003368', name: 'Mini Show laCreme Kids', price: 31.99, weight: '108g', desc: 'Bombons ao leite com recheio sabor leite', category: 'infantil' },
  { id: '1003698', name: 'Tablete laCreme Kids 130g', price: 26.49, weight: '130g', desc: 'Tablete ao leite com recheio sabor leite', category: 'infantil' },
  { id: '1003766', name: 'Drageados Dinossauros', price: 12.99, weight: '60g', desc: 'Balas de goma confeitadas e drageadas', category: 'infantil' },
  { id: '2005462', name: 'Pelúcia Dinossauro Dylan', price: 64.99, weight: '25cm', desc: 'Pelúcia colecionável - Linha Dinossauros', category: 'infantil' },
  { id: '2005460', name: 'Pelúcia Dinossauro Darla', price: 64.99, weight: '21cm', desc: 'Pelúcia colecionável - Linha Dinossauros', category: 'infantil' },
  { id: '2005461', name: 'Pelúcia Dinossauro Dustin', price: 64.99, weight: '22cm', desc: 'Pelúcia colecionável - Linha Dinossauros', category: 'infantil' },
  { id: '2005650', name: 'Pelúcias Ursinhos Carinhosos', price: 109.99, weight: 'Único', desc: 'Pelúcias oficiais Care Bears', category: 'infantil' },
  { id: '1003787', name: 'Bombons Chocomonstros Tatuagens', price: 31.99, weight: '120g', desc: 'Bombons doce de leite com cartela de tatuagens', category: 'infantil' },
  { id: '1003701', name: 'Tabletes Chocomonstros', price: 7.99, weight: '30g', desc: 'Tabletes de chocolate ao leite', category: 'infantil' },
  { id: '1003807', name: 'Copos Chocomonstros', price: 84.99, weight: '145g', desc: 'Bombons brigadeiro com copo colecionável', category: 'infantil' },
  { id: '1002646', name: 'Tablete com Confeitos', price: 19.29, weight: '115g', desc: 'Tablete ao leite com confeitos coloridos', category: 'infantil' },
  { id: '1003451', name: 'Drageados Chocomonstros', price: 21.29, weight: '100g', desc: 'Bala de goma drageada com chocolate', category: 'infantil' },
  { id: '1002783', name: 'Cubos Chocomonstros', price: 31.99, weight: '145g', desc: 'Bombons ao leite sabor brigadeiro', category: 'infantil' },
  { id: '1003493', name: 'Caixa Miau', price: 54.99, weight: '210g', desc: 'Chocolate em formato de língua de gato sortidos', category: 'infantil' },
  { id: '1003634', name: 'Miau Recheado Leite', price: 22.29, weight: '70g', desc: 'Chocolate ao leite com recheio em formato língua de gato', category: 'infantil' },
  { id: '1003632', name: 'Miau ao Leite', price: 22.29, weight: '70g', desc: 'Chocolate ao leite em formato de língua de gato', category: 'infantil' },
  { id: '1003633', name: 'Miau Mezzo', price: 22.29, weight: '70g', desc: 'Chocolate ao leite e branco em formato língua de gato', category: 'infantil' },

  // ===== PRESENTES =====
  { id: '1000137', name: 'MonteBello Tradicional', price: 17.99, weight: '90g', desc: 'Marshmallow coberto com chocolate ao leite', category: 'presentes' },
  { id: '1001335', name: 'MonteBello Maracujá', price: 17.99, weight: '90g', desc: 'Mousse de maracujá coberto com chocolate', category: 'presentes' },
  { id: '1001113', name: 'MonteBello Chocolate', price: 17.99, weight: '90g', desc: 'Mousse de chocolate coberto com chocolate', category: 'presentes' },
  { id: '2002357', name: 'Pão de Mel', price: 11.99, weight: '50g', desc: 'Pão de mel com doce de leite e chocolate 55%', category: 'presentes' },
  { id: '2003421', name: 'Caixa Presente P', price: 7.49, weight: '-', desc: 'Caixa pequena para personalização (sem trufas)', category: 'presentes' },
  { id: '2003420', name: 'Caixa Presente M', price: 9.99, weight: '-', desc: 'Caixa média para personalização (sem trufas)', category: 'presentes' },
  { id: '2003419', name: 'Caixa Presente G', price: 11.99, weight: '-', desc: 'Caixa grande para personalização (sem trufas)', category: 'presentes' },
  { id: 'cesta-lacreme', name: 'Cesta laCreme', price: 274.86, weight: 'Kit completo', desc: 'Kit completo com tabletes, trufas e Slack laCreme', category: 'presentes' },
  { id: '2002832', name: 'Pelúcia Urso Marrom G', price: 109.99, weight: '36cm', desc: 'Pelúcia ideal para montagem de kit', category: 'presentes' },
  { id: '2004616', name: 'Pelúcia Urso Laço de Cetim', price: 99.99, weight: '24cm', desc: 'Pelúcia clássica para presente', category: 'presentes' },
  { id: '2001204', name: 'Pelúcia Vaquinha Cremilda', price: 99.99, weight: '28cm', desc: 'Pelúcia mascote da linha Kids', category: 'presentes' },
  { id: '2002753', name: 'Pelúcia Gato Miau', price: 64.99, weight: '31cm', desc: 'Pelúcia mascote da linha Miau', category: 'presentes' },
  { id: '2002819', name: 'Pelúcia Cachorro com Pote', price: 84.99, weight: '22cm', desc: 'Pelúcia com pote para trufas', category: 'presentes' },
  { id: '2002831', name: 'Cartão Te Amo', price: 2.99, weight: '-', desc: 'Cartão temático para trufa 13,5g', category: 'presentes' },
  { id: '2002829', name: 'Cartão Gratidão', price: 2.99, weight: '-', desc: 'Cartão temático para trufa 13,5g', category: 'presentes' },
  { id: '2002830', name: 'Cartão Parabéns', price: 2.99, weight: '-', desc: 'Cartão temático para trufa 13,5g', category: 'presentes' },
  { id: '1002203', name: 'Chocoarte Gratidão', price: 16.99, weight: '40g', desc: 'Tablete decorado artesanalmente', category: 'presentes' },
  { id: '1000421', name: 'Chocoarte Parabéns', price: 16.99, weight: '40g', desc: 'Tablete decorado artesanalmente', category: 'presentes' },

  // ===== ACESSÓRIOS =====
  { id: '2004390', name: 'Caneca Grande Creme', price: 46.99, weight: '-', desc: 'Caneca temática "Você não pode comprar felicidade"', category: 'acessorios' },
  { id: '2004389', name: 'Caneca Grande Marrom', price: 46.99, weight: '-', desc: 'Caneca temática "Metade de mim quer chocolate"', category: 'acessorios' },
  { id: '2001256', name: 'Caneca laCreme Cremilda', price: 33.99, weight: '-', desc: 'Caneca da mascote Cremilda', category: 'acessorios' },
  { id: '2004386', name: 'Caneca Ryo Creme', price: 33.99, weight: '-', desc: 'Caneca elegante na cor creme', category: 'acessorios' },
  { id: '2004384', name: 'Caneca Ryo Marrom', price: 33.99, weight: '-', desc: 'Caneca elegante na cor marrom', category: 'acessorios' },
  { id: '2004385', name: 'Caneca LaNut', price: 37.49, weight: '-', desc: 'Caneca verde texturizada da linha LaNut', category: 'acessorios' },
  { id: '2004393', name: 'Caneca Drop Marrom', price: 23.49, weight: '-', desc: 'Caneca cônica marrom', category: 'acessorios' },
  { id: '2004391', name: 'Caneca Fusion Verde', price: 41.49, weight: '-', desc: 'Caneca dual color verde', category: 'acessorios' },
  { id: '2004392', name: 'Caneca Fusion Goiaba', price: 41.49, weight: '-', desc: 'Caneca dual color goiaba', category: 'acessorios' },
  { id: '2005925', name: 'Caneca Miau Preta e Branca', price: 31.99, weight: '-', desc: 'Caneca estampada com gatinhos', category: 'acessorios' },
  { id: '2005924', name: 'Caneca Miau Amarela', price: 31.99, weight: '-', desc: 'Caneca amarela estampada com gatinhos', category: 'acessorios' },
  { id: '2004381', name: 'Copo Bendito Cacao', price: 42.49, weight: '-', desc: 'Copo take away preto da linha Bendito Cacao', category: 'acessorios' },
  { id: '2004382', name: 'Caneca Feliz Hoje Marrom', price: 37.49, weight: '-', desc: 'Caneca temática estampada', category: 'acessorios' },
  { id: '2000753', name: 'Caneca Calda de Chocolate', price: 33.99, weight: '-', desc: 'Caneca com efeito calda derretida', category: 'acessorios' },
  { id: '2005943', name: 'Caneca Ursinhos Carinhosos', price: 39.49, weight: '-', desc: 'Caneca oficial Care Bears', category: 'acessorios' },
  { id: '2006355', name: 'Garrafa Térmica CS', price: 99.99, weight: '500ml', desc: 'Garrafa térmica em cores variadas', category: 'acessorios' },
  { id: '2006351', name: 'Copo Calda', price: 84.99, weight: '450ml', desc: 'Copo térmico 6h - efeito chocolate derretido', category: 'acessorios' },
  { id: '2005914', name: 'Copo Chocolate', price: 69.99, weight: '710ml', desc: 'Copo transparente com decoração de chocolate', category: 'acessorios' },
  { id: '2005979', name: 'Bolsa Puffer Chocolate', price: 189.99, weight: '-', desc: 'Bolsa puffer estilosa cor chocolate', category: 'acessorios' },
  { id: '2005980', name: 'Bolsa Puffer Creme', price: 189.99, weight: '-', desc: 'Bolsa puffer estilosa cor creme', category: 'acessorios' },
  { id: '2005909', name: 'Shoulder Bag CS', price: 109.99, weight: '-', desc: 'Bolsa transversal com pins decorativos', category: 'acessorios' },
  { id: '2005911', name: 'Nécessaire Puffer CS', price: 79.99, weight: '-', desc: 'Nécessaire puffer com pins', category: 'acessorios' },
  { id: '2005907', name: 'Chaveiro Premium CS', price: 34.99, weight: '-', desc: 'Chaveiro com 3 ícones Cacau Show', category: 'acessorios' },
  { id: '2005936', name: 'Chaveiros Sortidos CS', price: 16.99, weight: '-', desc: '7 modelos disponíveis - escolha seu favorito', category: 'acessorios' },
  { id: '2005929', name: 'Pins Sortidos CS', price: 11.99, weight: '-', desc: '7 modelos disponíveis para colecionar', category: 'acessorios' },
  { id: '2005985', name: 'Kit Pins Sortidos CS', price: 21.99, weight: '-', desc: 'Kit com 3 pins - chocolate ou fondue', category: 'acessorios' },
  { id: '2006249', name: 'Pelúcias Chocomigos', price: 42.49, weight: '14cm', desc: 'Caixa com pelúcia surpresa - 8 modelos', category: 'acessorios' }
];
